[package]
name = "atri_qq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ricq = "0.1.15"

serde = "1"
serde_json = "1"
toml = "0"

bytes = "1"
tracing = "0"
tracing-subscriber = { version = "0", features = ["fmt", "local-time"] }
async-trait = "0"
time = { version = "0", features = ["macros", "local-offset", "formatting"] }
regex = "1"
dashmap = "5"
libloading = "0"

skia-safe = "0"

[dependencies.tokio]
version = "1"
features = [
    "rt-multi-thread",
    "sync",
    "mio",
    "io-std"
]

[dependencies.reqwest]
version = "0"

[profile.release]
lto = true
opt-level = 'z'
incremental = false
strip = true
codegen-units = 1